# Generated by Django 4.2 on 2024-04-17 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ratings_Review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='id',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='newidsbds',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
