# Generated by Django 4.2 on 2024-04-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ratings_Review', '0002_remove_reviewrating_id_reviewrating_newidsbds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='newidsbds',
            new_name='id',
        ),
    ]
