# Generated by Django 4.2 on 2024-04-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ratings_Review', '0003_rename_newidsbds_reviewrating_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='review_id',
        ),
    ]
