# Generated by Django 4.2 on 2024-02-18 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_genre', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'ordering': ('type_genre',),
            },
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('show_title', models.CharField(max_length=250, unique=True)),
                ('show_description', models.TextField(blank=True)),
                ('show_writer', models.CharField(max_length=50)),
                ('show_released', models.DateField()),
                ('show_upload_date', models.DateField()),
                ('show_withdrawal_date', models.DateField(blank=True, null=True)),
                ('show_image', models.ImageField(blank=True, upload_to='movies')),
                ('show_available', models.BooleanField(default=True)),
                ('type_genre', models.ManyToManyField(to='mediaApp.genre')),
            ],
            options={
                'verbose_name': 'show',
                'verbose_name_plural': 'shows',
                'ordering': ('show_title',),
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mov_title', models.CharField(max_length=250, unique=True)),
                ('mov_description', models.TextField(blank=True)),
                ('mov_director', models.CharField(max_length=50)),
                ('mov_released', models.DateField()),
                ('mov_upload_date', models.DateField()),
                ('mov_withdrawal_date', models.DateField(blank=True, null=True)),
                ('mov_image', models.ImageField(blank=True, upload_to='movies/')),
                ('mov_available', models.BooleanField(default=True)),
                ('type_genre', models.ManyToManyField(to='mediaApp.genre')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'ordering': ('mov_title',),
            },
        ),
    ]
