# Generated by Django 4.2 on 2024-02-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='mov_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
