# Generated by Django 4.2 on 2024-02-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0002_movies_mov_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='mov_image_url',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
