# Generated by Django 4.2 on 2024-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0003_alter_movies_mov_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='mov_image',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='mov_image_url',
        ),
        migrations.AddField(
            model_name='movies',
            name='mov_icon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='mov_trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
