# Generated by Django 4.2 on 2024-02-19 22:26

from django.db import migrations, models
import mediaApp.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0004_remove_movies_mov_image_remove_movies_mov_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='mov_test',
            field=models.ImageField(blank=True, null=True, storage=mediaApp.custom_storage.CustomFileStorage(), upload_to='testFiles'),
        ),
    ]
