# Generated by Django 4.2 on 2024-02-19 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0005_movies_mov_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='mov_test',
            new_name='mov_icon',
        ),
    ]
