# Generated by Django 4.2 on 2024-02-19 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0006_rename_mov_test_movies_mov_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='mov_icon_url',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='mov_trailer_url',
        ),
    ]
