# Generated by Django 4.2 on 2024-02-20 00:12

from django.db import migrations, models
import mediaApp.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0007_remove_movies_mov_icon_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='mov_trailer',
            field=models.FileField(blank=True, null=True, storage=mediaApp.custom_storage.CustomFileStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_icon',
            field=models.ImageField(blank=True, null=True, storage=mediaApp.custom_storage.CustomFileStorage(), upload_to=''),
        ),
    ]
