# Generated by Django 4.2 on 2024-02-20 11:57

from django.db import migrations, models
import mediaApp.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0009_alter_movies_mov_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='mov_icon',
            field=models.ImageField(blank=True, null=True, storage=mediaApp.custom_storage.CustomFileStorage(), upload_to='Icons/'),
        ),
    ]
