# Generated by Django 4.2 on 2024-02-20 12:24

from django.db import migrations, models
import mediaApp.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0011_alter_movies_mov_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='mov_trailer',
            field=models.FileField(blank=True, null=True, storage=mediaApp.custom_storage.CustomFileStorage(), upload_to='MovieTrailers/'),
        ),
    ]
