# Generated by Django 4.2 on 2024-02-20 12:27

from django.db import migrations, models
import mediaApp.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0012_alter_movies_mov_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='mov_media',
            field=models.FileField(blank=True, null=True, storage=mediaApp.custom_storage.CustomFileStorage(), upload_to='MovieMedia/'),
        ),
    ]
