# Generated by Django 4.2 on 2024-02-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0013_movies_mov_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='mov_title',
            field=models.TextField(max_length=250, unique=True),
        ),
    ]
