# Generated by Django 4.2 on 2024-02-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0014_alter_movies_mov_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='mov_media',
        ),
        migrations.AddField(
            model_name='movies',
            name='mov_moviefile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_trailer',
            field=models.URLField(blank=True, null=True),
        ),
    ]
