# Generated by Django 4.2 on 2024-02-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0015_remove_movies_mov_media_movies_mov_moviefile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_title', models.TextField(max_length=50, unique=True)),
                ('row_director', models.CharField(blank=True, max_length=50, null=True)),
                ('row_content', models.ManyToManyField(blank=True, to='mediaApp.movies')),
                ('row_genre', models.ManyToManyField(blank=True, to='mediaApp.genre')),
            ],
        ),
    ]
