# Generated by Django 4.2 on 2024-02-22 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0016_mediarow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('con_title', models.TextField(max_length=250, unique=True)),
                ('con_description', models.TextField(blank=True)),
                ('con_released', models.DateField()),
                ('con_upload_date', models.DateField()),
                ('con_director', models.CharField(max_length=50)),
                ('con_withdrawal_date', models.DateField(blank=True, null=True)),
                ('con_icon', models.URLField(blank=True, null=True)),
                ('con_trailer', models.URLField(blank=True, null=True)),
                ('con_available', models.BooleanField(default=True)),
                ('con_genre', models.ManyToManyField(to='mediaApp.genre')),
            ],
            options={
                'ordering': ('con_title',),
            },
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
        migrations.AlterField(
            model_name='ContentRow',
            name='row_content',
            field=models.ManyToManyField(blank=True, to='mediaApp.content'),
        ),
    ]
