# Generated by Django 4.2 on 2024-02-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0017_content_delete_movies_alter_mediarow_row_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('con_title',), 'verbose_name': 'content', 'verbose_name_plural': 'content'},
        ),
        migrations.RemoveField(
            model_name='content',
            name='con_director',
        ),
    ]
