# Generated by Django 4.2 on 2024-02-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0018_alter_content_options_remove_content_con_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='ContentRow',
            name='row_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
