# Generated by Django 4.2 on 2024-02-22 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0019_mediarow_row_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_title', models.TextField(max_length=50, unique=True)),
                ('feat_position', models.IntegerField(blank=True, null=True)),
                ('feat_content', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mediaApp.content')),
            ],
        ),
    ]
