# Generated by Django 4.2 on 2024-02-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0020_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featured',
            options={'verbose_name': 'featured', 'verbose_name_plural': 'featured'},
        ),
        migrations.AlterField(
            model_name='featured',
            name='feat_title',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
