# Generated by Django 4.2 on 2024-02-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0022_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shows',
        ),
    ]
