# Generated by Django 4.2 on 2024-02-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0023_delete_shows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentrow',
            name='row_genre',
        ),
        migrations.AddField(
            model_name='contentrow',
            name='row_genre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaApp.genre'),
        ),
    ]
