# Generated by Django 4.2 on 2024-02-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0024_remove_contentrow_row_genre_contentrow_row_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentrow',
            old_name='row_content',
            new_name='row_contentSelected',
        ),
    ]
