# Generated by Django 4.2 on 2024-02-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0025_rename_row_content_contentrow_row_contentselected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentrow',
            old_name='row_contentSelected',
            new_name='row_content',
        ),
    ]
