# Generated by Django 4.2 on 2024-02-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0026_rename_row_contentselected_contentrow_row_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentrow',
            old_name='row_content',
            new_name='row_selectedContent',
        ),
    ]
