# Generated by Django 4.2 on 2024-02-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0027_rename_row_content_contentrow_row_selectedcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentrow',
            name='row_selectedContent',
        ),
    ]
