# Generated by Django 4.2 on 2024-02-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0028_remove_contentrow_row_selectedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrow',
            name='row_content',
            field=models.ManyToManyField(blank=True, to='mediaApp.content'),
        ),
    ]
