# Generated by Django 4.2 on 2024-02-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0029_contentrow_row_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='con_movie',
            field=models.BooleanField(default=True),
        ),
    ]
