# Generated by Django 4.2 on 2024-02-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0030_content_con_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='content',
        ),
        migrations.AddField(
            model_name='media',
            name='content',
            field=models.ManyToManyField(to='mediaApp.content'),
        ),
    ]
