# Generated by Django 4.2 on 2024-02-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0032_media_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='color',
        ),
        migrations.AddField(
            model_name='media',
            name='med_type',
            field=models.CharField(choices=[('show', 'Show'), ('movie', 'Movie'), ('extra', 'Extra')], default='movie', max_length=6),
        ),
    ]
