# Generated by Django 4.2 on 2024-02-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0033_remove_media_color_media_med_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='med_title',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
