# Generated by Django 4.2 on 2024-02-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0034_alter_media_med_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='con_movie',
        ),
        migrations.AddField(
            model_name='content',
            name='con_type',
            field=models.CharField(choices=[('show', 'Show'), ('movie', 'Movie')], default='movie', max_length=6),
        ),
    ]
