# Generated by Django 4.2 on 2024-02-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0035_remove_content_con_movie_content_con_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='med_pill',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
