# Generated by Django 4.2 on 2024-02-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0036_media_med_pill'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='med_desc',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
