# Generated by Django 4.2 on 2024-04-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0037_media_med_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='med_desc',
        ),
        migrations.RemoveField(
            model_name='media',
            name='med_type',
        ),
        migrations.RemoveField(
            model_name='media',
            name='med_url',
        ),
    ]
