# Generated by Django 4.2 on 2024-04-20 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0038_remove_media_med_desc_remove_media_med_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_title', models.TextField(max_length=250)),
                ('file_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
