# Generated by Django 4.2 on 2024-04-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0039_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='MediaFile',
        ),
    ]
