# Generated by Django 4.2 on 2024-04-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0040_rename_file_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, to='mediaApp.mediafile'),
        ),
        migrations.RemoveField(
            model_name='content',
            name='con_trailer',
        ),
        migrations.AddField(
            model_name='content',
            name='con_trailer',
            field=models.ManyToManyField(blank=True, null=True, to='mediaApp.mediafile'),
        ),
    ]
