# Generated by Django 4.2 on 2024-04-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0041_media_file_remove_content_con_trailer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='con_trailer',
            field=models.ManyToManyField(blank=True, to='mediaApp.mediafile'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ManyToManyField(blank=True, to='mediaApp.mediafile'),
        ),
    ]
