# Generated by Django 4.2 on 2024-04-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0042_alter_content_con_trailer_alter_media_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ('file_title',), 'verbose_name': 'mediaFile', 'verbose_name_plural': 'mediaFiles'},
        ),
        migrations.RemoveField(
            model_name='media',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='con_media',
            field=models.ManyToManyField(blank=True, to='mediaApp.media'),
        ),
    ]
