# Generated by Django 4.2 on 2024-04-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0043_alter_mediafile_options_remove_media_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='med_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
