# Generated by Django 4.2 on 2024-04-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0044_media_med_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='con_media',
        ),
        migrations.AddField(
            model_name='media',
            name='med_content',
            field=models.ManyToManyField(blank=True, to='mediaApp.content'),
        ),
    ]
