# Generated by Django 4.2 on 2024-04-20 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0045_remove_content_con_media_media_med_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='med_content',
        ),
        migrations.AddField(
            model_name='media',
            name='med_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaApp.content'),
        ),
    ]
