# Generated by Django 4.2 on 2024-04-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0046_remove_media_med_content_media_med_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='con_released',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='con_upload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
