# Generated by Django 4.2 on 2024-04-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0047_alter_content_con_released_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='med_title',
            field=models.TextField(default='Empty', max_length=250),
        ),
    ]
