# Generated by Django 4.2 on 2024-04-21 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0049_alter_media_med_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='con_trailer',
        ),
        migrations.AddField(
            model_name='content',
            name='con_trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaApp.mediafile'),
        ),
    ]
