# Generated by Django 4.2 on 2024-04-21 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0050_remove_content_con_trailer_content_con_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file',
        ),
        migrations.AddField(
            model_name='media',
            name='med_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaApp.mediafile'),
        ),
    ]
