# Generated by Django 4.2 on 2024-04-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0051_remove_media_file_media_med_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrow',
            name='row_type',
            field=models.CharField(choices=[('show', 'Show'), ('movie', 'Movie'), ('all', 'All')], default='all', max_length=6),
        ),
    ]
