# Generated by Django 4.2 on 2024-04-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0053_alter_contentrow_row_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrow',
            name='row_type',
            field=models.CharField(choices=[('show', 'Show'), ('movie', 'Movie'), ('allContent', 'All Content')], default='allContent', max_length=10),
        ),
    ]
