# Generated by Django 4.2 on 2024-04-21 16:52

from django.db import migrations, models
import mediaApp.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0054_alter_contentrow_row_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='mov_icon',
            field=models.ImageField(blank=True, null=True, storage=mediaApp.custom_storage.CustomFileStorage(), upload_to='testFiles'),
        ),
    ]
