# Generated by Django 4.2 on 2024-04-21 16:58

from django.db import migrations, models
import mediaApp.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0055_content_mov_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='mov_icon',
            field=models.ImageField(blank=True, null=True, storage=mediaApp.custom_storage.CustomFileStorage(), upload_to='Icons/'),
        ),
    ]
