# Generated by Django 4.2 on 2024-04-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0057_alter_content_mov_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='mov_icon',
        ),
    ]
