# Generated by Django 4.2 on 2024-04-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0058_remove_content_mov_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='con_genre',
        ),
        migrations.AddField(
            model_name='content',
            name='con_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaApp.genre'),
        ),
    ]
