# Generated by Django 4.2 on 2024-04-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0059_remove_content_con_genre_content_con_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrow',
            name='row_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaApp.genre'),
        ),
    ]
