# Generated by Django 4.2 on 2024-02-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediaApp', '0017_content_delete_movies_alter_mediarow_row_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_title', models.TextField(max_length=250, unique=True)),
                ('row_director', models.CharField(max_length=50)),
                ('row_content', models.ManyToManyField(blank=True, null=True, to='mediaApp.content')),
                ('row_genre', models.ManyToManyField(blank=True, null=True, to='mediaApp.genre')),
            ],
        ),
    ]
