# Generated by Django 4.2 on 2024-02-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_mediarow_delete_mediarows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ContentRow',
            name='row_title',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
