# Generated by Django 4.2 on 2024-02-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_mediarow_row_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ContentRow',
            name='row_director',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
