# Generated by Django 4.2 on 2024-02-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_mediarow_row_director'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentRow',
        ),
    ]
