# Generated by Django 4.2 on 2024-04-16 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('req_subject', models.TextField(max_length=50, unique=True)),
                ('req_description', models.TextField(blank=True, max_length=1000)),
                ('req_date_requested', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('req_category', models.CharField(choices=[('subscription', 'Subscription'), ('content', 'Watch Content'), ('watchy_exclusives', 'WatchY Exclusives'), ('account', 'My Account')], default='movie', max_length=17)),
            ],
            options={
                'ordering': ('req_date_requested',),
            },
        ),
    ]
