# Generated by Django 4.2 on 2024-04-16 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customerSupport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='req_status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('stuck', 'Stuck'), ('resolved', 'Resolved'), ('closed_not_resolved', 'Closed Not Resolved')], default='new', max_length=19),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='req_category',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('content', 'Watch Content'), ('watchy_exclusives', 'WatchY Exclusives'), ('account', 'My Account')], max_length=17),
        ),
    ]
