# Generated by Django 4.2 on 2024-04-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerSupport', '0003_alter_supportrequest_req_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='req_subject',
            field=models.TextField(max_length=15, unique=True),
        ),
    ]
