# Generated by Django 4.2 on 2024-04-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerSupport', '0005_alter_supportrequest_req_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='req_category',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('content', 'Watch Content'), ('watchy_exclusives', 'WatchY Exclusives'), ('account', 'My Account')], max_length=17, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='req_description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='req_status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('stuck', 'Stuck'), ('resolved', 'Resolved'), ('closed_not_resolved', 'Closed Not Resolved')], default='new', max_length=19, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='req_subject',
            field=models.TextField(max_length=15, verbose_name='Subject'),
        ),
    ]
