# Generated by Django 4.2 on 2024-04-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerSupport', '0006_alter_supportrequest_req_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='req_subject',
            field=models.TextField(max_length=30, verbose_name='Subject'),
        ),
    ]
